# Generated by Django 3.2.7 on 2021-09-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_pizzas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
            ],
        ),
    ]
