# Generated by Django 3.2.7 on 2021-10-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
