# Generated by Django 3.2.7 on 2021-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_messages_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(default='', editable=False, max_length=100000),
        ),
    ]
